### ISSUE TITLE
File Table Overflow. Number of files limit

### ISSUE THREAD

**Issue by fasterfox46** [bevry/watchr#104]
Please, I'll really appreciate if is possible o have an idea of this problem. Thanks.
I'm having the following error on Mac OS.

Probably due a limitation in the number of files inside a folder under watchr.

What is the maximum files o how to increase the default number? 

Error: ENFILE: file table overflow, open '/Users/IVC/javascript/test-watchr/node_modules/readdir-cluster/source/worker.js'
    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:20)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
/usr/local/bin/node[35030]: ../src/tracing/agent.cc:55:node::tracing::Agent::Agent(): Assertion `(uv_loop_init(&tracing_loop_)) == (0)' failed.
(libuv) kqueue(): Too many open files in system
child_process.js:120
  p.open(fd);
    ^

**Comment by balupton** [comment]
How many files are you attempting to watch?

**Comment by balupton** [comment]
Limitation of Node.js. Use watchman #91
