### ISSUE TITLE
Error in initial setup

### ISSUE THREAD

**Issue by matthew-dean** [bevry/watchr#69]
I've copied the sample from readme.md exactly, except I am passing in path: <string> instead of paths: <array>.

On first run, I get this error (full paths ommitted):

```
TypeError: listener must be a function
    at TypeError (native)
    at _Class.EventEmitter.removeListener (events.js:211:11)
    at _Class.listen (.../src/node_modules/watchr/out/lib/watchr.js:229:16)
    at _Class.listen (.../src/node_modules/watchr/out/lib/watchr.js:226:18)
    at _Class.setConfig (.../src/node_modules/watchr/out/lib/watchr.js:117:16)
    at new _Class (.../src/node_modules/watchr/out/lib/watchr.js:94:14)
    at createWatcher (.../src/node_modules/watchr/out/lib/watchr.js:684:17)
    at Object.watch (.../src/node_modules/watchr/out/lib/watchr.js:742:16)
```

**Comment by matthew-dean** [comment]
Never mind, I got the path to work by using paths: [ path ].
